// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightingsystem.proto

package ds.lightingsystem;

public final class LightingSystemImpl {
  private LightingSystemImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LightingSystem_SetLightLevelsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LightingSystem_SetLightLevelsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LightingSystem_SetLightLevelsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LightingSystem_SetLightLevelsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LightingSystem_SwitchLightRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LightingSystem_SwitchLightRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LightingSystem_SwitchLightResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LightingSystem_SwitchLightResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LightingSystem_SetLightScheduleRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LightingSystem_SetLightScheduleRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LightingSystem_SetLightScheduleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LightingSystem_SetLightScheduleResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024lightingsystem.proto\022\016LightingSystem\"=" +
      "\n\025SetLightLevelsRequest\022\021\n\tsystem_id\030\001 \001" +
      "(\t\022\021\n\tintensity\030\002 \001(\002\"9\n\026SetLightLevelsR" +
      "esponse\022\016\n\006status\030\001 \001(\010\022\017\n\007message\030\002 \001(\t" +
      "\"&\n\022SwitchLightRequest\022\020\n\010light_id\030\001 \001(\t" +
      "\"*\n\023SwitchLightResponse\022\023\n\013light_state\030\001" +
      " \001(\010\"e\n\027SetLightScheduleRequest\022\021\n\tsyste" +
      "m_id\030\001 \001(\t\022\022\n\nstart_time\030\002 \001(\003\022\020\n\010end_ti" +
      "me\030\003 \001(\003\022\021\n\tintensity\030\004 \001(\002\";\n\030SetLightS" +
      "cheduleResponse\022\016\n\006status\030\001 \001(\010\022\017\n\007messa" +
      "ge\030\002 \001(\t2\272\002\n\016LightingSystem\022c\n\016SetLightL" +
      "evels\022%.LightingSystem.SetLightLevelsReq" +
      "uest\032&.LightingSystem.SetLightLevelsResp" +
      "onse\"\000(\001\022X\n\013SwitchLight\022\".LightingSystem" +
      ".SwitchLightRequest\032#.LightingSystem.Swi" +
      "tchLightResponse\"\000\022i\n\020SetLightSchedule\022\'" +
      ".LightingSystem.SetLightScheduleRequest\032" +
      "(.LightingSystem.SetLightScheduleRespons" +
      "e\"\000(\001B)\n\021ds.lightingsystemB\022LightingSyst" +
      "emImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LightingSystem_SetLightLevelsRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LightingSystem_SetLightLevelsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LightingSystem_SetLightLevelsRequest_descriptor,
        new java.lang.String[] { "SystemId", "Intensity", });
    internal_static_LightingSystem_SetLightLevelsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LightingSystem_SetLightLevelsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LightingSystem_SetLightLevelsResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_LightingSystem_SwitchLightRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_LightingSystem_SwitchLightRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LightingSystem_SwitchLightRequest_descriptor,
        new java.lang.String[] { "LightId", });
    internal_static_LightingSystem_SwitchLightResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_LightingSystem_SwitchLightResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LightingSystem_SwitchLightResponse_descriptor,
        new java.lang.String[] { "LightState", });
    internal_static_LightingSystem_SetLightScheduleRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_LightingSystem_SetLightScheduleRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LightingSystem_SetLightScheduleRequest_descriptor,
        new java.lang.String[] { "SystemId", "StartTime", "EndTime", "Intensity", });
    internal_static_LightingSystem_SetLightScheduleResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_LightingSystem_SetLightScheduleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LightingSystem_SetLightScheduleResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
