// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightingsystem.proto

package ds.lightingsystem;

public interface SetLightScheduleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LightingSystem.SetLightScheduleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string system_id = 1;</code>
   */
  java.lang.String getSystemId();
  /**
   * <code>string system_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getSystemIdBytes();

  /**
   * <code>int64 start_time = 2;</code>
   */
  long getStartTime();

  /**
   * <code>int64 end_time = 3;</code>
   */
  long getEndTime();

  /**
   * <code>float intensity = 4;</code>
   */
  float getIntensity();
}
