// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightingsystem.proto

package ds.lightingsystem;

public interface SetLightLevelsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LightingSystem.SetLightLevelsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string system_id = 1;</code>
   */
  java.lang.String getSystemId();
  /**
   * <code>string system_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getSystemIdBytes();

  /**
   * <code>float intensity = 2;</code>
   */
  float getIntensity();
}
