// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightingsystem.proto

package ds.lightingsystem;

public interface SwitchLightRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LightingSystem.SwitchLightRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string light_id = 1;</code>
   */
  java.lang.String getLightId();
  /**
   * <code>string light_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getLightIdBytes();

  /**
   * <code>bool status = 2;</code>
   */
  boolean getStatus();
}
