// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightingsystem.proto

package ds.lightingsystem;

public interface SwitchLightResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LightingSystem.SwitchLightResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool light_state = 1;</code>
   */
  boolean getLightState();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
