// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: applianceoptimization.proto

package ds.applicationoptimization;

public interface SetApplianceScheduleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApplicationOptimization.SetApplianceScheduleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string appliance_id = 1;</code>
   */
  java.lang.String getApplianceId();
  /**
   * <code>string appliance_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getApplianceIdBytes();

  /**
   * <code>int64 start_time = 2;</code>
   */
  long getStartTime();

  /**
   * <code>int64 end_time = 3;</code>
   */
  long getEndTime();
}
