// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: applicationoptimization.proto

package ds.applicationoptimization;

public interface SetApplianceLimitRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApplicationOptimization.SetApplianceLimitRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string applianceID = 1;</code>
   */
  java.lang.String getApplianceID();
  /**
   * <code>string applianceID = 1;</code>
   */
  com.google.protobuf.ByteString
      getApplianceIDBytes();

  /**
   * <code>float limit = 2;</code>
   */
  float getLimit();
}
