// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: applicationoptimization.proto

package ds.applicationoptimization;

public interface SetApplianceScheduleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApplicationOptimization.SetApplianceScheduleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
