// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: applicationoptimization.proto

package ds.applicationoptimization;

public interface SetApplianceModeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApplicationOptimization.SetApplianceModeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string appliance_id = 1;</code>
   */
  java.lang.String getApplianceId();
  /**
   * <code>string appliance_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getApplianceIdBytes();

  /**
   * <code>string mode = 2;</code>
   */
  java.lang.String getMode();
  /**
   * <code>string mode = 2;</code>
   */
  com.google.protobuf.ByteString
      getModeBytes();

  /**
   * <code>string location = 3;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 3;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
