// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: applicationoptimization.proto

package ds.applicationoptimization;

public interface SetApplianceModeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ApplicationOptimization.SetApplianceModeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   */
  boolean getStatus();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
