// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energymonitoring.proto

package ds.energymonitoring;

public interface EnergyUsageHistoryDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnergyMonitoring.EnergyUsageHistoryData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 date_time = 1;</code>
   */
  long getDateTime();

  /**
   * <code>float energy_usage = 2;</code>
   */
  float getEnergyUsage();
}
