// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energymonitoring.proto

package ds.energymonitoring;

public final class EnergyMonitoringImpl {
  private EnergyMonitoringImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnergyMonitoring_GetEnergyUsageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnergyMonitoring_GetEnergyUsageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnergyMonitoring_GetEnergyUsageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnergyMonitoring_GetEnergyUsageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnergyMonitoring_UsageBySourceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnergyMonitoring_UsageBySourceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnergyMonitoring_UsageBySourceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnergyMonitoring_UsageBySourceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnergyMonitoring_GetEnergyUsageHistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnergyMonitoring_GetEnergyUsageHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EnergyMonitoring_EnergyUsageHistoryData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EnergyMonitoring_EnergyUsageHistoryData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026energymonitoring.proto\022\020EnergyMonitori" +
      "ng\"P\n\025GetEnergyUsageRequest\022\021\n\tdevice_id" +
      "\030\001 \001(\t\022\022\n\nstart_time\030\002 \001(\003\022\020\n\010end_time\030\003" +
      " \001(\003\"W\n\026GetEnergyUsageResponse\022\032\n\022total_" +
      "energy_usage\030\001 \001(\002\022!\n\031average_power_cons" +
      "umption\030\002 \001(\002\"O\n\024UsageBySourceRequest\022\021\n" +
      "\tsource_id\030\001 \001(\t\022\022\n\nstart_time\030\002 \001(\003\022\020\n\010" +
      "end_time\030\003 \001(\003\"-\n\025UsageBySourceResponse\022" +
      "\024\n\014energy_usage\030\001 \001(\002\"1\n\034GetEnergyUsageH" +
      "istoryRequest\022\021\n\tdevice_id\030\001 \001(\t\"A\n\026Ener" +
      "gyUsageHistoryData\022\021\n\tdate_time\030\001 \001(\003\022\024\n" +
      "\014energy_usage\030\002 \001(\0022\337\002\n\020EnergyMonitoring" +
      "\022e\n\016GetEnergyUsage\022\'.EnergyMonitoring.Ge" +
      "tEnergyUsageRequest\032(.EnergyMonitoring.G" +
      "etEnergyUsageResponse\"\000\022m\n\026GetEnergyUsag" +
      "eBySource\022&.EnergyMonitoring.UsageBySour" +
      "ceRequest\032\'.EnergyMonitoring.UsageBySour" +
      "ceResponse\"\0000\001\022u\n\025GetEnergyUsageHistory\022" +
      "..EnergyMonitoring.GetEnergyUsageHistory" +
      "Request\032(.EnergyMonitoring.EnergyUsageHi" +
      "storyData\"\0000\001B-\n\023ds.energymonitoringB\024En" +
      "ergyMonitoringImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_EnergyMonitoring_GetEnergyUsageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EnergyMonitoring_GetEnergyUsageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnergyMonitoring_GetEnergyUsageRequest_descriptor,
        new java.lang.String[] { "DeviceId", "StartTime", "EndTime", });
    internal_static_EnergyMonitoring_GetEnergyUsageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EnergyMonitoring_GetEnergyUsageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnergyMonitoring_GetEnergyUsageResponse_descriptor,
        new java.lang.String[] { "TotalEnergyUsage", "AveragePowerConsumption", });
    internal_static_EnergyMonitoring_UsageBySourceRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_EnergyMonitoring_UsageBySourceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnergyMonitoring_UsageBySourceRequest_descriptor,
        new java.lang.String[] { "SourceId", "StartTime", "EndTime", });
    internal_static_EnergyMonitoring_UsageBySourceResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_EnergyMonitoring_UsageBySourceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnergyMonitoring_UsageBySourceResponse_descriptor,
        new java.lang.String[] { "EnergyUsage", });
    internal_static_EnergyMonitoring_GetEnergyUsageHistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_EnergyMonitoring_GetEnergyUsageHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnergyMonitoring_GetEnergyUsageHistoryRequest_descriptor,
        new java.lang.String[] { "DeviceId", });
    internal_static_EnergyMonitoring_EnergyUsageHistoryData_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_EnergyMonitoring_EnergyUsageHistoryData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EnergyMonitoring_EnergyUsageHistoryData_descriptor,
        new java.lang.String[] { "DateTime", "EnergyUsage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
