// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energymonitoring.proto

package ds.energymonitoring;

public interface GetEnergyUsageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnergyMonitoring.GetEnergyUsageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *specifies the device name and identification
   * </pre>
   *
   * <code>string device_id = 1;</code>
   */
  java.lang.String getDeviceId();
  /**
   * <pre>
   *specifies the device name and identification
   * </pre>
   *
   * <code>string device_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>int64 start_time = 2;</code>
   */
  long getStartTime();

  /**
   * <code>int64 end_time = 3;</code>
   */
  long getEndTime();
}
