// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energymonitoring.proto

package ds.energymonitoring;

public interface GetEnergyUsageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnergyMonitoring.GetEnergyUsageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float total_energy_usage = 1;</code>
   */
  float getTotalEnergyUsage();

  /**
   * <code>float average_power_consumption = 2;</code>
   */
  float getAveragePowerConsumption();
}
