// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energymonitoring.proto

package ds.energymonitoring;

public interface GetEnergyUsageHistoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnergyMonitoring.GetEnergyUsageHistoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string device_id = 1;</code>
   */
  java.lang.String getDeviceId();
  /**
   * <code>string device_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();
}
