// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energymonitoring.proto

package ds.energymonitoring;

import java.util.List;

import com.google.protobuf.Timestamp;

import ds.energymonitoring.GetEnergyUsageRequest.Builder;

/**
 * Protobuf type {@code EnergyMonitoring.GetEnergyUsageResponse}
 */
public  final class GetEnergyUsageResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EnergyMonitoring.GetEnergyUsageResponse)
    GetEnergyUsageResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetEnergyUsageResponse.newBuilder() to construct.
  private GetEnergyUsageResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetEnergyUsageResponse() {
    totalEnergyUsage_ = 0F;
    averagePowerConsumption_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetEnergyUsageResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 13: {

            totalEnergyUsage_ = input.readFloat();
            break;
          }
          case 21: {

            averagePowerConsumption_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.energymonitoring.EnergyMonitoringImpl.internal_static_EnergyMonitoring_GetEnergyUsageResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.energymonitoring.EnergyMonitoringImpl.internal_static_EnergyMonitoring_GetEnergyUsageResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.energymonitoring.GetEnergyUsageResponse.class, ds.energymonitoring.GetEnergyUsageResponse.Builder.class);
  }

  public static final int TOTAL_ENERGY_USAGE_FIELD_NUMBER = 1;
  private float totalEnergyUsage_;
  /**
   * <code>float total_energy_usage = 1;</code>
   */
  public float getTotalEnergyUsage() {
    return totalEnergyUsage_;
  }

  public static final int AVERAGE_POWER_CONSUMPTION_FIELD_NUMBER = 2;
  private float averagePowerConsumption_;
  /**
   * <code>float average_power_consumption = 2;</code>
   */
  public float getAveragePowerConsumption() {
    return averagePowerConsumption_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (totalEnergyUsage_ != 0F) {
      output.writeFloat(1, totalEnergyUsage_);
    }
    if (averagePowerConsumption_ != 0F) {
      output.writeFloat(2, averagePowerConsumption_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (totalEnergyUsage_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(1, totalEnergyUsage_);
    }
    if (averagePowerConsumption_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, averagePowerConsumption_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.energymonitoring.GetEnergyUsageResponse)) {
      return super.equals(obj);
    }
    ds.energymonitoring.GetEnergyUsageResponse other = (ds.energymonitoring.GetEnergyUsageResponse) obj;

    boolean result = true;
    result = result && (
        java.lang.Float.floatToIntBits(getTotalEnergyUsage())
        == java.lang.Float.floatToIntBits(
            other.getTotalEnergyUsage()));
    result = result && (
        java.lang.Float.floatToIntBits(getAveragePowerConsumption())
        == java.lang.Float.floatToIntBits(
            other.getAveragePowerConsumption()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOTAL_ENERGY_USAGE_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getTotalEnergyUsage());
    hash = (37 * hash) + AVERAGE_POWER_CONSUMPTION_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getAveragePowerConsumption());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.energymonitoring.GetEnergyUsageResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.energymonitoring.GetEnergyUsageResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.energymonitoring.GetEnergyUsageResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.energymonitoring.GetEnergyUsageResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.energymonitoring.GetEnergyUsageResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.energymonitoring.GetEnergyUsageResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.energymonitoring.GetEnergyUsageResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.energymonitoring.GetEnergyUsageResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.energymonitoring.GetEnergyUsageResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.energymonitoring.GetEnergyUsageResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.energymonitoring.GetEnergyUsageResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.energymonitoring.GetEnergyUsageResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.energymonitoring.GetEnergyUsageResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code EnergyMonitoring.GetEnergyUsageResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EnergyMonitoring.GetEnergyUsageResponse)
      ds.energymonitoring.GetEnergyUsageResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.energymonitoring.EnergyMonitoringImpl.internal_static_EnergyMonitoring_GetEnergyUsageResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.energymonitoring.EnergyMonitoringImpl.internal_static_EnergyMonitoring_GetEnergyUsageResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.energymonitoring.GetEnergyUsageResponse.class, ds.energymonitoring.GetEnergyUsageResponse.Builder.class);
    }

    // Construct using ds.energymonitoring.GetEnergyUsageResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      totalEnergyUsage_ = 0F;

      averagePowerConsumption_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.energymonitoring.EnergyMonitoringImpl.internal_static_EnergyMonitoring_GetEnergyUsageResponse_descriptor;
    }

    @java.lang.Override
    public ds.energymonitoring.GetEnergyUsageResponse getDefaultInstanceForType() {
      return ds.energymonitoring.GetEnergyUsageResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.energymonitoring.GetEnergyUsageResponse build() {
      ds.energymonitoring.GetEnergyUsageResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.energymonitoring.GetEnergyUsageResponse buildPartial() {
      ds.energymonitoring.GetEnergyUsageResponse result = new ds.energymonitoring.GetEnergyUsageResponse(this);
      result.totalEnergyUsage_ = totalEnergyUsage_;
      result.averagePowerConsumption_ = averagePowerConsumption_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.energymonitoring.GetEnergyUsageResponse) {
        return mergeFrom((ds.energymonitoring.GetEnergyUsageResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.energymonitoring.GetEnergyUsageResponse other) {
      if (other == ds.energymonitoring.GetEnergyUsageResponse.getDefaultInstance()) return this;
      if (other.getTotalEnergyUsage() != 0F) {
        setTotalEnergyUsage(other.getTotalEnergyUsage());
      }
      if (other.getAveragePowerConsumption() != 0F) {
        setAveragePowerConsumption(other.getAveragePowerConsumption());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.energymonitoring.GetEnergyUsageResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.energymonitoring.GetEnergyUsageResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private float totalEnergyUsage_ ;
    /**
     * <code>float total_energy_usage = 1;</code>
     */
    public float getTotalEnergyUsage() {
      return totalEnergyUsage_;
    }
    /**
     * <code>float total_energy_usage = 1;</code>
     */
    public Builder setTotalEnergyUsage(float value) {
      
      totalEnergyUsage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float total_energy_usage = 1;</code>
     */
    public Builder clearTotalEnergyUsage() {
      
      totalEnergyUsage_ = 0F;
      onChanged();
      return this;
    }

    private float averagePowerConsumption_ ;
    /**
     * <code>float average_power_consumption = 2;</code>
     */
    public float getAveragePowerConsumption() {
      return averagePowerConsumption_;
    }
    /**
     * <code>float average_power_consumption = 2;</code>
     */
    public Builder setAveragePowerConsumption(float value) {
      
      averagePowerConsumption_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float average_power_consumption = 2;</code>
     */
    public Builder clearAveragePowerConsumption() {
      
      averagePowerConsumption_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }

	public Builder addAllUsageData(List<GetEnergyUsageResponse> energyUsageList) {
		// TODO Auto-generated method stub
		return null;
	}

	public Object setTimestamp(Timestamp timestamp) {
		// TODO Auto-generated method stub
		return null;
	}

	public Object setDeviceId(String deviceId) {
		// TODO Auto-generated method stub
		return "";
	}
	public Object setStartTime(long value) {
	      
	      long startTime_ = value;
	      onChanged();
	      return this;
	    }
	public Object setEndTime(long value) {
	      
	      long endTime_ = value;
	      onChanged();
	      return this;
	    }
    // @@protoc_insertion_point(builder_scope:EnergyMonitoring.GetEnergyUsageResponse)
  }

  // @@protoc_insertion_point(class_scope:EnergyMonitoring.GetEnergyUsageResponse)
  private static final ds.energymonitoring.GetEnergyUsageResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.energymonitoring.GetEnergyUsageResponse();
  }

  public static ds.energymonitoring.GetEnergyUsageResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetEnergyUsageResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetEnergyUsageResponse>() {
    @java.lang.Override
    public GetEnergyUsageResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetEnergyUsageResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetEnergyUsageResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetEnergyUsageResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.energymonitoring.GetEnergyUsageResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

