// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energymonitoring.proto

package ds.energymonitoring;

public interface UsageBySourceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnergyMonitoring.UsageBySourceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float energy_usage = 1;</code>
   */
  float getEnergyUsage();
}
