// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: energymonitoring.proto

package ds.energymonitoring;

public interface UsageBySourceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EnergyMonitoring.UsageBySourceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string source_id = 1;</code>
   */
  java.lang.String getSourceId();
  /**
   * <code>string source_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getSourceIdBytes();

  /**
   * <code>int64 start_time = 2;</code>
   */
  long getStartTime();

  /**
   * <code>int64 end_time = 3;</code>
   */
  long getEndTime();
}
